# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A single SwiZ estimation for beta regression
#'
#' @param theta initial values (coef + log-precision)
#' @param pi initial estimator
#' @param x matrix of design
#' @param seed integer representing the state fir random number generation
#' @param maxit maximum number of iteration
#' @param eps_f tolerance
#' @param eps_g tolerance
NULL

#' @title Random generation of beta regression responses
#'
#' @param x a matrix of design (first column must be one to include an intercept)
#' @param beta a vector of regression coefficient
#' @param phi precision parameter
#' @param seed integer representing the state fir random number generation
#' @export
rbetareg <- function(x, beta, phi, seed) {
    .Call('_ImpBootPaper_rbetareg', PACKAGE = 'ImpBootPaper', x, beta, phi, seed)
}

#' @title Maximum likelihood estimation of beta regression
#'
#' @param start initial values (coef + log-precision)
#' @param y responses
#' @param x matrix of design
#' @param maxit maximum number of iteration
#' @param eps_f tolerance
#' @param eps_g tolerance
optim_mle_betareg <- function(start, y, x, maxit = 300L, eps_f = 1e-6, eps_g = 1e-6) {
    .Call('_ImpBootPaper_optim_mle_betareg', PACKAGE = 'ImpBootPaper', start, y, x, maxit, eps_f, eps_g)
}

#' @title SwiZ distribution for beta regression
#'
#' @param pi initial estimator
#' @param x matrix of design
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
swiz_dist_betareg <- function(pi, x, B, seed, ncores) {
    .Call('_ImpBootPaper_swiz_dist_betareg', PACKAGE = 'ImpBootPaper', pi, x, B, seed, ncores)
}

#' @title Parametric bootstrap distribution for beta regression
#'
#' @param start initial estimator
#' @param x matrix of design
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
par_bootstrap_mle_betareg <- function(start, x, B, seed, ncores) {
    .Call('_ImpBootPaper_par_bootstrap_mle_betareg', PACKAGE = 'ImpBootPaper', start, x, B, seed, ncores)
}

#' @title Studentized parametric bootstrap distribution for beta regression
#'
#' @param theta initial estimator
#' @param boot matrix, parametric bootstrap
#' @param x matrix of design
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
par_boott_betareg <- function(theta, boot, x, B, seed, ncores) {
    .Call('_ImpBootPaper_par_boott_betareg', PACKAGE = 'ImpBootPaper', theta, boot, x, B, seed, ncores)
}

#' @title BCa acceleration parameter for beta regression
#'
#' @param start MLE
#' @param y observations
#' @param x matrix of design
acceleration_betareg <- function(start, y, x) {
    .Call('_ImpBootPaper_acceleration_betareg', PACKAGE = 'ImpBootPaper', start, y, x)
}

#' @title Random generation of Lomax distribution
#'
#' @param n sample size
#' @param b positive parameter
#' @param q positive parameter
#' @param seed integer representing the state fir random number generation
#' @export
rlomax <- function(n, b, q, seed) {
    .Call('_ImpBootPaper_rlomax', PACKAGE = 'ImpBootPaper', n, b, q, seed)
}

#' @title Maximum likelihood estimation of beta regression
#'
#' @param start initial values
#' @param y observations
#' @param maxit maximum number of iteration
#' @param eps_f tolerance
#' @param eps_g tolerance
optim_mle_lomax <- function(start, y, maxit = 500L, eps_f = 1e-10, eps_g = 1e-10) {
    .Call('_ImpBootPaper_optim_mle_lomax', PACKAGE = 'ImpBootPaper', start, y, maxit, eps_f, eps_g)
}

#' @title SwiZ distribution for Lomax distribution
#'
#' @param pi initial estimator
#' @param n sample size
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
swiz_dist_lomax <- function(pi, n, B, seed, ncores) {
    .Call('_ImpBootPaper_swiz_dist_lomax', PACKAGE = 'ImpBootPaper', pi, n, B, seed, ncores)
}

#' @title Parametric bootstrap distribution for Lomax distribution
#'
#' @param start initial estimator
#' @param n sample size
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
par_bootstrap_mle_lomax <- function(start, n, B, seed, ncores) {
    .Call('_ImpBootPaper_par_bootstrap_mle_lomax', PACKAGE = 'ImpBootPaper', start, n, B, seed, ncores)
}

#' @title Studentized parametric bootstrap distribution for beta regression
#'
#' @param theta initial estimator
#' @param boot matrix, parametric bootstrap
#' @param n sample size
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
#' @param robust if true uses robust estimation of covariance
par_boott_lomax <- function(theta, boot, n, B, seed, ncores, robust = FALSE) {
    .Call('_ImpBootPaper_par_boott_lomax', PACKAGE = 'ImpBootPaper', theta, boot, n, B, seed, ncores, robust)
}

#' @title BCa acceleration parameter for Lomax distribution
#'
#' @param start MLE
#' @param y observations
acceleration_lomax <- function(start, y) {
    .Call('_ImpBootPaper_acceleration_lomax', PACKAGE = 'ImpBootPaper', start, y)
}

#' @title Random generation of t regression responses
#'
#' @param x a matrix of design (first column must be one to include an intercept)
#' @param beta a vector of regression coefficient
#' @param sig2 variance parameter
#' @param nu degrees of freedom
#' @param seed integer representing the state fir random number generation
#' @export
rtreg <- function(x, beta, sig2, nu, seed) {
    .Call('_ImpBootPaper_rtreg', PACKAGE = 'ImpBootPaper', x, beta, sig2, nu, seed)
}

#' @title Maximum likelihood estimation of t regression
#'
#' @param start initial values (coef + log-variance + log-dof)
#' @param y responses
#' @param x matrix of design
#' @param maxit maximum number of iteration
#' @param eps_f tolerance
#' @param eps_g tolerance
optim_mle_treg <- function(start, y, x, maxit = 500L, eps_f = 1e-10, eps_g = 1e-10) {
    .Call('_ImpBootPaper_optim_mle_treg', PACKAGE = 'ImpBootPaper', start, y, x, maxit, eps_f, eps_g)
}

#' @title SwiZ distribution for t regression
#'
#' @param pi initial estimator
#' @param x matrix of design
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
swiz_dist_treg <- function(pi, x, B, seed, ncores) {
    .Call('_ImpBootPaper_swiz_dist_treg', PACKAGE = 'ImpBootPaper', pi, x, B, seed, ncores)
}

#' @title Parametric bootstrap distribution for t regression
#'
#' @param start initial estimator
#' @param x matrix of design
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
par_bootstrap_mle_treg <- function(start, x, B, seed, ncores) {
    .Call('_ImpBootPaper_par_bootstrap_mle_treg', PACKAGE = 'ImpBootPaper', start, x, B, seed, ncores)
}

#' @title Studentized parametric bootstrap distribution for t regression
#'
#' @param theta initial estimator
#' @param boot matrix, parametric bootstrap
#' @param x matrix of design
#' @param B number of SwiZ estimates
#' @param seed integer representing the state fir random number generation
#' @param ncores number of cores (OpenMP parallelisation)
#' @param robust if true uses robust estimation of covariance
par_boott_treg <- function(theta, boot, x, B, seed, ncores, robust = FALSE) {
    .Call('_ImpBootPaper_par_boott_treg', PACKAGE = 'ImpBootPaper', theta, boot, x, B, seed, ncores, robust)
}

#' @title BCa acceleration parameter for t regression
#'
#' @param start MLE
#' @param y observations
#' @param x matrix of design
acceleration_treg <- function(start, y, x) {
    .Call('_ImpBootPaper_acceleration_treg', PACKAGE = 'ImpBootPaper', start, y, x)
}

