# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rbetareg <- function(x, beta, phi, seed) {
    .Call('_ImpBootPaper_rbetareg', PACKAGE = 'ImpBootPaper', x, beta, phi, seed)
}

optim_mle <- function(theta, y, x, maxit = 300L, eps_f = 1e-6, eps_g = 1e-6) {
    .Call('_ImpBootPaper_optim_mle', PACKAGE = 'ImpBootPaper', theta, y, x, maxit, eps_f, eps_g)
}

of_mle <- function(theta, y, x) {
    .Call('_ImpBootPaper_of_mle', PACKAGE = 'ImpBootPaper', theta, y, x)
}

of_swiz <- function(theta, pi, x, seed) {
    .Call('_ImpBootPaper_of_swiz', PACKAGE = 'ImpBootPaper', theta, pi, x, seed)
}

swiz_fn <- function(theta, pi, x, seed) {
    .Call('_ImpBootPaper_swiz_fn', PACKAGE = 'ImpBootPaper', theta, pi, x, seed)
}

swiz_gr <- function(theta, pi, x, seed) {
    .Call('_ImpBootPaper_swiz_gr', PACKAGE = 'ImpBootPaper', theta, pi, x, seed)
}

optim_swiz <- function(theta, pi, x, seed) {
    .Call('_ImpBootPaper_optim_swiz', PACKAGE = 'ImpBootPaper', theta, pi, x, seed)
}

swiz_dist <- function(pi, x, B, seed, ncores) {
    .Call('_ImpBootPaper_swiz_dist', PACKAGE = 'ImpBootPaper', pi, x, B, seed, ncores)
}

par_bootstrap_mle <- function(start, x, B, seed, ncores) {
    .Call('_ImpBootPaper_par_bootstrap_mle', PACKAGE = 'ImpBootPaper', start, x, B, seed, ncores)
}

par_boott <- function(theta, boot, x, B, seed, ncores) {
    .Call('_ImpBootPaper_par_boott', PACKAGE = 'ImpBootPaper', theta, boot, x, B, seed, ncores)
}

